uploads = []
outputs = []

[[generated]]
id = "NACEDA_hfCZm8wksX9g_T"
uri = "file://artifacts/gbcshs/public/hero-bg.png"
type = "image"
title = "Late night coding session"

[[generated]]
id = "-sL_5449KXuhggxXzdS7t"
uri = "file://artifacts/gbcshs/public/abstract-tech.png"
type = "image"
title = "Tech abstract crest"
